# Generated by Django 2.2 on 2019-04-17 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('hotel_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('category', models.ForeignKey(blank=True, max_length=140, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Category')),
                ('location', models.ForeignKey(blank=True, max_length=140, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Location')),
            ],
            options={
                'ordering': ['hotel_name'],
            },
        ),
    ]
